export const reactToggle: string;
export const reactToggleScreenreaderOnly: string;
export const reactToggleDisabled: string;
export const reactToggleTrack: string;
export const reactToggleChecked: string;
export const reactToggleTrackCheck: string;
export const reactToggleTrackX: string;
export const reactToggleThumb: string;
export const reactToggleFocus: string;
